name: npm-publish
on:
  push:
    branches:
      - master # Change this to your default branch
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm install
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: build site
        run: npm run build-site
      - name: push
        uses: github-actions-x/commit@v2.8
        with:
          github-token: ${{ secrets.PAGE_TOKKEN }}
          push-branch: git_page
          commit-message: 'update site'
          force-add: 'true'
          force-push: 'true'
          name: koory1st
          email: liguenator@gmail.com
