name: npm-publish
on:
  push:
    branches:
      - master # Change this to your default branch
jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm install
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_AUTH_TOKEN }}
  publish-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm install
      - name: pull branch git_page
        run: |
          git config --global user.name 'koory1st'
          git config --global user.email 'liguenator@gmail.com'
          git remote set-url origin https://x-access-token:${{ secrets.PAGE_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git pull origin git_page:git_page
          git checkout git_page
          git merge -m "update page" origin/master
      - name: build site
        run: npm i && cd site && npm i && npm run build && cd ..
      - name: push branch git_page
        run: |
          git add docs/
          git commit -am "update page"
          git push --set-upstream origin git_page
