name: npm-publish
on:
  push:
    branches:
      - master # Change this to your default branch
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm install
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: build
        run: npm run build-site
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: git_page # The branch the action should deploy to.
          folder: docs # The folder the action should deploy.
          token: ${{ secrets.PAGE_TOKKEN }}
